services:
  app:
    build: .
    container_name: laravel-filament-app
    restart: always
    ports:
      - "80:80" # Accederás vía http://ip-del-servidor:8080
    volumes:
      - .:/var/www/html
    networks:
      - shared_db_network
    env_file:
      - .env
  scheduler:
    build: .
    container_name: laravel-filament-scheduler
    restart: always
    depends_on:
      - app
    volumes:
      - .:/var/www/html
    networks:
      - shared_db_network
    env_file:
      - .env
    command: php artisan schedule:work

networks:
  shared_db_network:
    external: true # Indica que la red ya existe y no debe crearla de cero