services:
  app:
    build: .
    container_name: laravel-filament-app
    restart: always
    ports:
      - "8080:80" # Accederás vía http://ip-del-servidor:8080
    volumes:
      - .:/var/www/html
    networks:
      - shared_db_network
    env_file:
      - .env

networks:
  shared_db_network:
    external: true # Indica que la red ya existe y no debe crearla de cero